M: 4
context_aspect_ratio: 1.0
context_scale: !!python/tuple
- 0.85
- 1.0
decoder_depth: 2
embed_dim: 128
enc_depth: 6
enc_heads: 4
img_size: 64
in_chans: 3
lr: 0.001
m: 0.996
m_start_end: !!python/tuple
- 0.996
- 1.0
patch_size: 8
target_aspect_ratio: !!python/tuple
- 0.75
- 1.5
target_scale: !!python/tuple
- 0.15
- 0.2
weight_decay: 0.05
